import React, { useState } from "react";
import StaffRow from "../components/StaffRow.js";

function StaffPage() {
    const [results, getOutcome] = useState([]);
    const obtainStaff = () => {
        fetch("https://randomuser.me/api/?results=10")
        .then((response) => response.json())
        .then((response) => { getOutcome(response.results); })
        .catch(() => {
            alert("Well, the Randomness of the internet dictated that the Random User Generator is down")
        });
    };
        return (
            <>
            <article>
                <p className="paragraphOffset">The table below generates a random person
                    and adds them to the table each time one of the buttons is pushed.
                    Names are generated from the <a href="https://randomuser.me/" 
                    target="blank">Random User Generator</a> webpage.
                </p>
                
                <p className="paragraphOffset">
                    Generate a staff member by clicking here.
                <button id="serverGenerated" onClick={obtainStaff} value="add">Staff Generated by the <strong>Server</strong></button>
            </p>

            <table className="randomTable">
                <caption class="randomTable">Name, Email, Phone, and Location</caption>
                <thead>
                    <tr>
                        <th>Portrait</th>
                        <th>Name &amp; Email</th>
                        <th>Phone</th>
                        <th>City</th>
                    </tr>
                </thead>
                <tbody>
                    {results.map((staff, i) => <StaffRow person={staff} key={i} />)}
                </tbody>
            </table>
            </article>
            </>
        );
    };

export default StaffPage;